### ISSUE TITLE
插件首次加载启动会报错

### ISSUE THREAD

**Issue by yuan488** [OREOCODEDEV/nonebot-plugin-servicestate#8]
插件首次加载启动会报错
![IMG_20230307_021728](https://user-images.githubusercontent.com/69119229/223196918-d4d62157-3312-498c-b00b-0b7fc83543a6.jpg)

**Comment by yuan488** [comment]
在该位置新建了空白的config.txt也是报错，内容如下:
`TypeError: list indices must be integers or slices, not str`

**Comment by OREOCODEDEV** [comment]
啊，commit的时候不小心关掉了你的issue，你在Bot目录下使用命令 `nb plugin install nonebot-plugin-servicestate --upgrade -i https://pypi.python.org/simple` 更新一下我刚刚推上去的版本应该就好了

**Comment by yuan488** [comment]
感谢大佬，问题已解决。
